[project]
name = "file-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "inquirer>=3.4.1",
    "pyyaml>=6.0.3",
    "typer>=0.20.0",
    "types-pyyaml>=6.0.12.20250915",
]
